version: '3.7'
services:

  pyrogram-service:

    container_name: ssgv-pyrogram

    build:
      context: .
      dockerfile: Dockerfile

    command: python3 main.py

    ports:
      - 8000:8000

    volumes:
      - .:/src
